### ISSUE TITLE
Dependency on Styled-Components 2.0.1 breaks glam

### ISSUE THREAD

**Issue by kitten** [threepointone/glam#23]
I've just looked through the code and discovered this: https://github.com/threepointone/glam/blob/master/src/parseCSS.js#L5

We weren't using this file ourselves anymore in v2, so in 2.0.1 we removed `styled-components/lib/utils/autoprefix`. It's probably a better idea to vendor it or fix the version to 2.0.0 for now

**Comment by threepointone** [comment]
thanks for the headsup!

**Comment by kitten** [comment]
Haha, sorry, It's not really a headsup :( 2.0.1 is already released. I only discovered this dependency today

**Comment by threepointone** [comment]
No worries, gathered as much. All good 👍🏽

**Comment by tkh44** [comment]
Thanks @philpl
