### ISSUE TITLE
Composing with computed selectors broken

### ISSUE THREAD

**Issue by hamlim** [threepointone/glam#26]
Title might be a bit confusing, however I stumbled upon this use case and subsequent quirky behavior today:
I wanted to style a check on a checkbox using the sibling label element's `:after` element. 

```Javascript
const Component = _ => (
  <div>
    <input className={input} />
    <label className={label}>Label</label>
  </div>
)

const input = css`
  /* some styles here */
  &:checked + ${label}:after { // <--   This breaks (but I wasn't sure why until I looked at the compiled css)
    /* some more styles here */
  }
`
const label = css`
  /* some label styles here */
`
```

Expected Output:
```CSS
.input:checked + .label:after {
  /* styles here */
}
```
Actual Output:
```CSS
.input:checked + var(--css-y0e8lq-0):after {
  /* styles here */
}
```

As far as I can tell this might not actually be supported, so if thats the case then feel free to close, but if you have any tips on how I might be able to get this to work that would be greatly appreciated. 

Also not sure if there is some kind of heuristic that can be used to check if someone tries to use another classname like this inside another call to `css` to make it easy to either test for and/or provide warnings about doing so.

**Comment by tkh44** [comment]
It is not supported, unfortunately. I think one day we will be able to parse the template literal and make better decisions on what to turn into a var, but it's not in there now.

**Comment by hamlim** [comment]
Thanks for getting back to this, I figured it probably wouldn't work. Lucky for me css has other options to pick from when selecting elements so I might just use an id or data attribute to target the label.
