### ISSUE TITLE
Something's up with display "flex" auto-prefix

### ISSUE THREAD

**Issue by jossmac** [threepointone/glam#34]
Declaring `display: flex;` on a div returns:

```css
display: -webkit-box,-moz-box,-ms-flexbox,-webkit-flex,flex;
```

https://www.webpackbin.com/bins/-KynjoyF2whPpxdS-E3m

**Comment by lesha1201** [comment]
I'm going to fix it.

**Comment by dannya** [comment]
@jossmac I'm getting the same issue when using your `react-images` library - do you know of a workaround for this?

**Comment by dannya** [comment]
@lesha1201 for an extra datapoint, I'm seeing this on a `h4` element selector, and also when using a standard `class` selector (like `.h4`) as well (using `Parcel` v2 bundler).

**Comment by dannya** [comment]
@jossmac did you close this because it's no longer a problem? If so, I'd very much appreciate a pointer!

**Comment by lesha1201** [comment]
@dannya I don't think this project is maintained anymore. Last commit was 3 years ago

**Comment by dannya** [comment]
@lesha1201 seems to be the case, sadly.

For anyone who encounters this issue, there is a workaround as described here: https://github.com/jossmac/react-images/issues/382#issue-631001064

> To fix, add space after flex to fix the issue but no prefix is added.
> i.e `display: 'flex '`
